# import Error from '../../../shared.gql'

input UserInput {
	email: String!
	password: String!
}

type LoginResponse {
  errors: [Error!]
  sessionId: String
}

type Mutation {
	login(input: UserInput!): LoginResponse!
}